<?php
/**
 * Write config.php inside the container (first install only), then run migrations.
 *
 *   docker exec -e DB_PASS='...' jvacations php deploy/docker/make-config.php
 *
 * Reads the password from the environment so special characters survive intact.
 * Never overwrites an existing config.php.
 */
declare(strict_types=1);

// deploy/ is inside the document root: refuse to run over HTTP.
if (PHP_SAPI !== 'cli') { http_response_code(403); exit("Run this from the command line.\n"); }

$root = dirname(__DIR__, 2);          // /var/www/html
chdir($root);

if (file_exists("$root/config.php")) {
    echo "ℹ config.php already exists — left untouched.\n";
} else {
    $pass = getenv('DB_PASS') ?: '';
    if ($pass === '') exit("❌ DB_PASS is empty. Pass it with:  docker exec -e DB_PASS='...' …\n");

    $config = [
        'db' => [
            'host'    => getenv('DB_HOST') ?: 'jvacations-db',
            'port'    => (int) (getenv('DB_PORT') ?: 3306),
            'name'    => getenv('DB_NAME') ?: 'jvacations',
            'user'    => getenv('DB_USER') ?: 'jvacations',
            'pass'    => $pass,
            'charset' => 'utf8mb4',
        ],
        'timezone'       => getenv('APP_TZ') ?: 'Africa/Cairo',
        'session_name'   => 'jv_session',
        'default_locale' => getenv('APP_LOCALE') ?: 'ar',
    ];
    $php = "<?php\n// Generated by deploy/docker/make-config.php — environment-specific, never commit.\ndeclare(strict_types=1);\n\nreturn "
         . var_export($config, true) . ";\n";
    file_put_contents("$root/config.php", $php);
    echo "✓ config.php written\n";
}

// docker exec runs as root; Apache reads as www-data.
@chown("$root/config.php", 'www-data');
@chgrp("$root/config.php", 'www-data');
@chmod("$root/config.php", 0640);
echo "✓ config.php owned by www-data (0640)\n";

require __DIR__ . '/migrate.php';
